Feature/list page
SelcoD/CampingFriends pull request #5
Opened 2023-07-07 14:09 UTC by SelcoD

If anybody can help me with the header, i would be very thankful.
I cant style the header, any ideas ?
Thx!

2023-07-07 14:25 UTC, JonasDaJones commented
you could try to give the header another name as Header my be a next.js option (I had that issue with Setting).

2023-07-07 14:55 UTC, SelcoD commented
changed it to StyledHeader everywhere but it not works, i will change it back,'I will style it later, first of all, do you think this pull request  can be closed ? it schould be the complete US1. Thx

2023-07-08 15:05 UTC, SelcoD commented
Fixed the bug in the header.

2023-07-08 15:11 UTC, vaupunkt commented on components/CampingCard.js
> +import React from "react";
you don't have to import react 😊

2023-07-08 15:14 UTC, vaupunkt commented on pages/index.js
> +import { campingTrips } from "../data/campingTrips";
you can delete these

2023-07-08 15:15 UTC, vaupunkt commented on pages/ListPage.js
> +      </Footer>
this makes more sense in your index.js, as it will stay the same no matter what component you are rendering in the main-part of your app?

2023-07-08 15:18 UTC, vaupunkt commented on pages/ListPage.js
> +          </Card>
I don't understand why you have the Card-Component here at this point and then again inside the campingCard.js

2023-07-08 15:19 UTC, vaupunkt commented on components/CampingCard.js
> +    </Card>
if the camping card is the card itself, you don't need to call it a card at this point here again?

2023-07-08 15:21 UTC, vaupunkt commented on styles/styles.js
> +  background: linear-gradient(to right, #e66465, #9198e5);
you are giving every element a background gradient by hand - you could just add it to your body once in the globalStyles

2023-07-08 15:22 UTC, vaupunkt commented on pages/ListPage.js
> +import React from "react";
no need to import react as far as i know

2023-07-08 15:24 UTC, vaupunkt requested changes
There are some points where you can improve your code :) 
You are rendering the card component twice which leads to a doubled card in your preview. you can change that 💪

Also you already created many empty components which you don't need at this point

2023-07-08 15:28 UTC, SelcoD commented
I did some changes, some code was unnecessary and i styled the Body.

2023-07-10 08:38 UTC, merged